services:
  node:
    depends_on:
      - mariadb
    build:
      context: .
    volumes:
      - ./src:/app/src/
      - ./public:/app/public
  mariadb:
    image: mariadb:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
